// This file was generated by ecm_setup_version(): DO NOT EDIT!

#ifndef MAIA_VERSION_H
#define MAIA_VERSION_H

#define MAIA_VERSION_STRING "0.2.0"
#define MAIA_VERSION_MAJOR 0
#define MAIA_VERSION_MINOR 2
#define MAIA_VERSION_PATCH 0
#define MAIA_VERSION ((0<<16)|(2<<8)|(0))

#endif
